/**
 * 英文/常见拼写 → 中文词，用于与 mock 数据（中文地名）交叉搜索。
 * key 均为小写。
 */
export const DESTINATION_SEARCH_ALIASES = {
  thailand: '泰国',
  thai: '泰国',
  bangkok: '曼谷',
  chiangmai: '清迈',
  vietnam: '越南',
  hanoi: '河内',
  japan: '日本',
  tokyo: '东京',
  osaka: '大阪',
  nepal: '尼泊尔',
  usa: '美国',
  us: '美国',
  america: '美国',
  unitedstates: '美国',
  spain: '西班牙',
  australia: '澳大利亚',
  sydney: '悉尼',
  peru: '秘鲁',
  cambodia: '柬埔寨',
  angkor: '吴哥',
  morocco: '摩洛哥',
  iceland: '冰岛',
  georgia: '格鲁吉亚',
  tbilisi: '第比利斯',
  korea: '韩国',
  seoul: '首尔',
  busan: '釜山',
  portugal: '葡萄牙',
  egypt: '埃及',
  cairo: '开罗',
  france: '法国',
  germany: '德国',
  uk: '英国',
  britain: '英国',
  england: '英国',
  italy: '意大利',
  greece: '希腊',
  turkey: '土耳其',
  india: '印度',
  singapore: '新加坡',
  malaysia: '马来西亚',
  indonesia: '印度尼西亚',
  bali: '巴厘岛',
  philippines: '菲律宾',
  mexico: '墨西哥',
  canada: '加拿大',
  nz: '新西兰',
  newzealand: '新西兰',
  france: '法国',
  paris: '巴黎',
  germany: '德国',
  berlin: '柏林',
  munich: '慕尼黑',
  uk: '英国',
  london: '伦敦',
  scotland: '苏格兰',
  edinburgh: '爱丁堡',
  italy: '意大利',
  rome: '罗马',
  venice: '威尼斯',
  florence: '佛罗伦萨',
  indonesia: '印度尼西亚',
  bali: '巴厘岛',
  yogyakarta: '日惹',
  srilanka: '斯里兰卡',
  'sri lanka': '斯里兰卡',
  colombo: '科伦坡',
  malaysia: '马来西亚',
  kualalumpur: '吉隆坡',
  penang: '槟城',
  turkey: '土耳其',
  istanbul: '伊斯坦布尔',
  cappadocia: '卡帕多奇亚',
  mexico: '墨西哥',
  cancun: '坎昆',
  tulum: '图卢姆',
  czech: '捷克',
  prague: '布拉格',
  vienna: '维也纳',
  greece: '希腊',
  athens: '雅典',
  santorini: '圣托里尼',
  mykonos: '米克诺斯',
  singapore: '新加坡',
  canada: '加拿大',
  vancouver: '温哥华',
  banff: '班夫',
  jasper: '贾斯珀',
  argentina: '阿根廷',
  buenosaires: '布宜诺斯艾利斯',
  iguazu: '伊瓜苏',
  patagonia: '巴塔哥尼亚',
  norway: '挪威',
  lofoten: '罗弗敦',
  tromso: '特罗姆瑟',
  sweden: '瑞典',
  stockholm: '斯德哥尔摩',
  kiruna: '基律纳',
  netherlands: '荷兰',
  amsterdam: '阿姆斯特丹',
  holland: '荷兰',
  switzerland: '瑞士',
  zurich: '苏黎世',
  interlaken: '因特拉肯',
  lucerne: '琉森',
  jungfrau: '少女峰',
  hungary: '匈牙利',
  budapest: '布达佩斯',
  croatia: '克罗地亚',
  dubrovnik: '杜布罗夫尼克',
  split: '斯普利特',
  plitvice: '十六湖',
  finland: '芬兰',
  helsinki: '赫尔辛基',
  rovaniemi: '罗瓦涅米',
  denmark: '丹麦',
  copenhagen: '哥本哈根',
  legoland: '乐高',
  chile: '智利',
  santiago: '圣地亚哥',
  valparaiso: '瓦尔帕莱索',
  atacama: '阿塔卡马',
  'south africa': '南非',
  southafrica: '南非',
  capetown: '开普敦',
  poland: '波兰',
  warsaw: '华沙',
  krakow: '克拉科夫',
  ireland: '爱尔兰',
  dublin: '都柏林',
  galway: '高威',
  jordan: '约旦',
  amman: '安曼',
  petra: '佩特拉',
  wadirum: '瓦迪拉姆',
  deadsea: '死海',
  tunisia: '突尼斯',
  carthage: '迦太基',
  sidi: '西迪布赛义德',
  brazil: '巴西',
  rio: '里约',
  riodejaneiro: '里约热内卢',
  tanzania: '坦桑尼亚',
  serengeti: '塞伦盖蒂',
  zanzibar: '桑给巴尔',
  ngorongoro: '恩戈罗',
  armenia: '亚美尼亚',
  yerevan: '埃里温',
  sevan: '塞凡湖',
  peru: '秘鲁',
  lima: '利马',
  cusco: '库斯科',
  cuzco: '库斯科',
  machupicchu: '马丘比丘',
  rainbowmountain: '彩虹山',
  namibia: '纳米比亚',
  sossusvlei: '索斯斯黎',
  kenya: '肯尼亚',
  masaimara: '马赛马拉',
  nairobi: '内罗毕',
  myanmar: '缅甸',
  yangon: '仰光',
  bagan: '蒲甘',
  mandalay: '曼德勒',
  inle: '茵莱湖',
  laos: '老挝',
  luangprabang: '琅勃拉邦',
  vangvieng: '万荣',
  uzbekistan: '乌兹别克斯坦',
  tashkent: '塔什干',
  samarkand: '撒马尔罕',
  bukhara: '布哈拉',
  khiva: '希瓦',
  montenegro: '黑山',
  kotor: '科托尔',
  serbia: '塞尔维亚',
  belgrade: '贝尔格莱德',
  marrakech: '马拉喀什',
  marrakesh: '马拉喀什',
  fes: '菲斯',
  fez: '菲斯',
  chefchaouen: '舍夫沙万',
  merzouga: '梅尔祖卡',
  sahara: '撒哈拉',
  reykjavik: '雷克雅未克',
  goldencircle: '黄金圈',
  jokulsarlon: '杰古沙龙',
  mongolia: '蒙古',
  ulaanbaatar: '乌兰巴托',
  terelj: '特勒吉',
  bhutan: '不丹',
  thimphu: '廷布',
  paro: '帕罗',
  taktsang: '虎穴寺',
  ethiopia: '埃塞俄比亚',
  addis: '亚的斯亚贝巴',
  lalibela: '拉利贝拉',
  iran: '伊朗',
  tehran: '德黑兰',
  isfahan: '伊斯法罕',
  shiraz: '设拉子',
  persepolis: '波斯波利斯',
  uae: '阿联酋',
  dubai: '迪拜',
  abudhabi: '阿布扎比',
  philippines: '菲律宾',
  palawan: '巴拉望',
  elnido: '爱妮岛',
  coron: '科隆',
  kathmandu: '加德满都',
  pokhara: '博卡拉',
  phewa: '费瓦湖',
  hochiminh: '越南',
  saigon: '越南',
  hcmc: '越南',
  muine: '越南',
  dalat: '越南',
  nhatrang: '越南',
  hokkaido: '日本',
  sapporo: '日本',
  otaru: '日本',
  furano: '日本',
  asahikawa: '日本',
  abashiri: '日本',
  qatar: '卡塔尔',
  doha: '卡塔尔',
  oman: '阿曼',
  muscat: '阿曼',
  nizwa: '阿曼',
  tasmania: '澳大利亚',
  hobart: '澳大利亚',
  launceston: '澳大利亚',
  bolivia: '玻利维亚',
  uyuni: '玻利维亚',
  lapaz: '玻利维亚',
  colombia: '哥伦比亚',
  bogota: '哥伦比亚',
  medellin: '哥伦比亚',
  cartagena: '哥伦比亚',
  skye: '英国',
  portree: '英国',
  reunion: '留尼汪',
  jeju: '韩国',
  jejudo: '韩国',
  madagascar: '马达加斯加',
  antananarivo: '马达加斯加',
  morondava: '马达加斯加',
  sabah: '马来西亚',
  kotakinabalu: '马来西亚',
  kinabalu: '马来西亚',
  uruguay: '乌拉圭',
  montevideo: '乌拉圭',
  colonia: '乌拉圭',
  ecuador: '厄瓜多尔',
  galapagos: '厄瓜多尔',
  quito: '厄瓜多尔',
  banos: '厄瓜多尔',
  cuenca: '厄瓜多尔',
  brunei: '文莱',
  bandar: '文莱',
  cyprus: '塞浦路斯',
  nicosia: '塞浦路斯',
  paphos: '塞浦路斯',
  ayianapa: '塞浦路斯',
  slovenia: '斯洛文尼亚',
  ljubljana: '斯洛文尼亚',
  bled: '斯洛文尼亚',
  postojna: '斯洛文尼亚',
  panama: '巴拿马',
  panamacity: '巴拿马',
  sanblas: '巴拿马',
}

export function normalizeSearchText(val) {
  return (val || '').toString().toLowerCase().normalize('NFC').trim()
}

/** 返回用于匹配的小写关键词列表（含别名展开） */
export function searchQueryNeedles(rawQuery) {
  const q = normalizeSearchText(rawQuery)
  if (!q) return []
  const aliasZh = DESTINATION_SEARCH_ALIASES[q]
  const needles = [q]
  if (aliasZh) needles.push(normalizeSearchText(aliasZh))
  return [...new Set(needles.filter(Boolean))]
}

export function textMatchesNeedles(text, needles) {
  if (!needles.length) return true
  const hay = normalizeSearchText(text)
  return needles.some((n) => n && hay.includes(n))
}

/** 攻略卡片：标题、目的地、作者、标签 */
export function matchesGuideCard(item, rawQuery) {
  const needles = searchQueryNeedles(rawQuery)
  if (!needles.length) return true
  const tags = item.tags || []
  const fields = [item.title, item.destination, item.author, ...tags]
  return fields.some((f) => textMatchesNeedles(f, needles))
}

/** 目的地：名称、国家、地区 */
export function matchesDestinationCard(dest, rawQuery) {
  const needles = searchQueryNeedles(rawQuery)
  if (!needles.length) return true
  const fields = [dest.name, dest.country, dest.region, dest.continent, ...(dest.tags || [])]
  return fields.some((f) => textMatchesNeedles(f, needles))
}
